name: Build Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cài Theos
        uses: Randomblock1/theos-action@v1

      - name: Build package (.deb)
        run: |
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom26-deb
          path: packages/*.deb
